site_name: Forlinx Embedded Docs

site_url: https://forlinxembedded.github.io/forlinx-online-docs/

theme:
  name: material
  logo: images/forlinxembedded.png
  palette:
    primary:
      main: "#123456"     # 主色调
      light: "#56789a"
      dark: "#0f1a2b"
    accent:
      main: "#abcdef"     # 强调色

  font:
    text: "Open Sans"
    code: "Fira Code"

  
nav:
  - 首页: index.md
  - 硬件文档:
      - i.MX6ULL 简介: hardware/imx6ull-zh.md
      - 烧写系统: hardware/烧写系统.md

repo_url: https://forlinxembedded.github.io/forlinx-online-docs/
edit_uri: edit/main/docs/


plugins:
  - with-pdf

# 可选：自定义输出路径
with-pdf:
  output_path: pdf/forlinx-docs.pdf
